//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment5_2.Santosh_ref {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Santosh_ref.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Flight_Lookup", ReplyAction="http://tempuri.org/IService1/Flight_LookupResponse")]
        string Flight_Lookup(string ToFrom);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Flight_Lookup", ReplyAction="http://tempuri.org/IService1/Flight_LookupResponse")]
        System.Threading.Tasks.Task<string> Flight_LookupAsync(string ToFrom);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/sendEmail", ReplyAction="http://tempuri.org/IService1/sendEmailResponse")]
        void sendEmail(string rece, string msg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/sendEmail", ReplyAction="http://tempuri.org/IService1/sendEmailResponse")]
        System.Threading.Tasks.Task sendEmailAsync(string rece, string msg);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Assignment5_2.Santosh_ref.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Assignment5_2.Santosh_ref.IService1>, Assignment5_2.Santosh_ref.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Flight_Lookup(string ToFrom) {
            return base.Channel.Flight_Lookup(ToFrom);
        }
        
        public System.Threading.Tasks.Task<string> Flight_LookupAsync(string ToFrom) {
            return base.Channel.Flight_LookupAsync(ToFrom);
        }
        
        public void sendEmail(string rece, string msg) {
            base.Channel.sendEmail(rece, msg);
        }
        
        public System.Threading.Tasks.Task sendEmailAsync(string rece, string msg) {
            return base.Channel.sendEmailAsync(rece, msg);
        }
    }
}
